@startuml Update Booking (PUT)
header Hotel Booking Sequence Diagram
title "Update Booking (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:Database" as Database

client->server ++:req.put('/api/v1/bookings/:id')
server->routerBookings ++:app.use('/api/v1/bookings', bookings)
routerBookings -> controllersBookings ++:updateBooking()

' Check existing booking
controllersBookings->modelBooking ++:findById(req.params.id)
modelBooking ->Database ++: BookingSchema
Database --> modelBooking --: booking
modelBooking --> controllersBookings --: booking

' Update booking
controllersBookings->modelBooking ++:findByIdAndUpdate(req.params.id, req.body)
modelBooking ->Database ++: BookingSchema
Database --> modelBooking --: updatedBooking
controllersBookings <-- modelBooking --:updatedBooking
controllersBookings->client --:response

@enduml